# -*- coding: utf-8 -*-
"""SuperShop_DataMinin Lab project .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_kT2CUNGuLzshycwdNB592W9QxI4yIIQ

# 🛒 SuperShop Data Mining
## Customer Behavior Analysis & Intelligent Retail Decision Support System

---

### 📚 Course Information

- **Institution:** Green University of Bangladesh
- **Semester:** Fall 2025

### 👥 Team Members
| Name | ID |
|------|----|
| MD.Ratul Hasan | 221902181 |
| Afroza Akter Naznin | 221902132 |

### 📊 Dataset
- **Name:** Online Retail II (UCI)
- **Source:** [Kaggle](https://www.kaggle.com/datasets/mashlyn/online-retail-ii-uci)

---

## 📋 Table of Contents

1. [Setup & Installation](#1)
2. [Data Loading](#2)
3. [Module 1: Data Preprocessing](#3)
4. [Module 2: Feature Engineering](#4)
5. [Module 3: Exploratory Data Analysis (EDA)](#5)
6. [Module 4: Dimensionality Reduction](#6)
7. [Module 5: Association Rule Mining (FP-Growth)](#7)
8. [Module 6: Customer Segmentation (Clustering)](#8)
9. [Module 7: Classification Models](#9)
10. [Module 8: Ensemble Learning](#10)
11. [Module 9: Anomaly Detection](#11)
12. [Conclusion & Business Insights](#12)

---
<a id='1'></a>
# 1️⃣ Setup & Installation

প্রথমে প্রয়োজনীয় libraries install এবং import করবো।
"""

# Install required libraries
!pip install mlxtend -q
!pip install umap-learn -q
!pip install xgboost -q
!pip install openpyxl -q

print("✅ All packages installed successfully!")

# Import Libraries

# Data Manipulation
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Preprocessing
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV

# Dimensionality Reduction
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
import umap

# Association Rule Mining (FP-Growth)
from mlxtend.frequent_patterns import fpgrowth, association_rules
from mlxtend.preprocessing import TransactionEncoder

# Clustering
from sklearn.cluster import KMeans, DBSCAN, AgglomerativeClustering
from sklearn.metrics import silhouette_score
from scipy.cluster.hierarchy import dendrogram, linkage

# Classification
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.ensemble import VotingClassifier, StackingClassifier, AdaBoostClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier

# Evaluation Metrics
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score, roc_curve

# Anomaly Detection
from sklearn.ensemble import IsolationForest
from sklearn.neighbors import LocalOutlierFactor
from sklearn.svm import OneClassSVM

# Warnings
import warnings
warnings.filterwarnings('ignore')

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
plt.style.use('seaborn-v0_8-whitegrid')

print("✅ All libraries imported successfully!")

"""---
<a id='2'></a>
# 2️⃣ Data Loading

Kaggle থেকে dataset load করবো।
"""

# Option 1: Upload from local machine
from google.colab import files

print("📁 Please upload the 'online_retail_II.xlsx' or 'online_retail_II.csv' file")
uploaded = files.upload()

# Load the dataset
# Check file extension and load accordingly

file_name = list(uploaded.keys())[0]

if file_name.endswith('.xlsx'):
    # Load Excel file (may have multiple sheets)
    df = pd.read_excel(file_name, sheet_name=None)
    # Combine all sheets
    df = pd.concat(df.values(), ignore_index=True)
elif file_name.endswith('.csv'):
    df = pd.read_csv(file_name, encoding='unicode_escape')
else:
    print("❌ Unsupported file format. Please upload .xlsx or .csv")

# Display basic info
print(f"✅ Dataset loaded successfully!")
print(f"📊 Shape: {df.shape[0]:,} rows × {df.shape[1]} columns")
print(f"\n📋 Columns: {list(df.columns)}")

# Display first few rows
df.head(10)

# Dataset Info
print("="*60)
print("📊 DATASET INFORMATION")
print("="*60)
df.info()

# Statistical Summary
print("="*60)
print("📈 STATISTICAL SUMMARY")
print("="*60)
df.describe()

"""---
<a id='3'></a>
# 3️⃣ Module 1: Data Preprocessing


- Missing values handle করা
- Cancelled orders আলাদা করা
- Outliers remove করা
- Data types ঠিক করা
"""

# Create a copy of original data
df_original = df.copy()

print("📊 Original Dataset Shape:", df.shape)

# Check missing values
print("="*60)
print("❓ MISSING VALUES ANALYSIS")
print("="*60)

missing = df.isnull().sum()
missing_percent = (missing / len(df)) * 100

missing_df = pd.DataFrame({
    'Missing Count': missing,
    'Missing %': missing_percent.round(2)
})

print(missing_df[missing_df['Missing Count'] > 0])

# Visualize missing values
plt.figure(figsize=(10, 5))
colors = ['#2ecc71' if x == 0 else '#e74c3c' for x in missing]
plt.bar(missing.index, missing.values, color=colors)
plt.title('Missing Values by Column', fontsize=14, fontweight='bold')
plt.xlabel('Columns')
plt.ylabel('Missing Count')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Step 1: Handle Column Names (standardize)
df.columns = df.columns.str.strip().str.replace(' ', '_')
print("📋 Standardized Columns:", list(df.columns))

# Step 2: Remove rows with missing Customer ID
# Customer ID ছাড়া RFM analysis সম্ভব না

customer_col = [col for col in df.columns if 'customer' in col.lower()][0]
print(f" Customer column identified: {customer_col}")

before = len(df)
df = df.dropna(subset=[customer_col])
after = len(df)

print(f" Removed {before - after:,} rows with missing Customer ID")
print(f" Remaining rows: {after:,}")

# Step 3: Identify and separate cancelled orders
# Invoice starting with 'C' indicates cancellation

invoice_col = [col for col in df.columns if 'invoice' in col.lower()][0]
print(f"🔍 Invoice column identified: {invoice_col}")

# Convert to string for checking
df[invoice_col] = df[invoice_col].astype(str)

# Separate cancelled orders
df_cancelled = df[df[invoice_col].str.startswith('C')].copy()
df = df[~df[invoice_col].str.startswith('C')].copy()

print(f"🚫 Cancelled orders: {len(df_cancelled):,}")
print(f"✅ Valid orders: {len(df):,}")

# Step 4: Handle negative quantities (returns)
quantity_col = [col for col in df.columns if 'quantity' in col.lower()][0]
print(f"🔍 Quantity column identified: {quantity_col}")

negative_qty = (df[quantity_col] <= 0).sum()
print(f"📦 Rows with zero or negative quantity: {negative_qty:,}")

# Remove negative quantities
df = df[df[quantity_col] > 0]
print(f"✅ After removing: {len(df):,} rows")

# Step 5: Handle negative or zero prices
price_col = [col for col in df.columns if 'price' in col.lower()][0]
print(f"🔍 Price column identified: {price_col}")

negative_price = (df[price_col] <= 0).sum()
print(f"💰 Rows with zero or negative price: {negative_price:,}")

# Remove zero/negative prices
df = df[df[price_col] > 0]
print(f"✅ After removing: {len(df):,} rows")

# Step 6: Convert data types
date_col = [col for col in df.columns if 'date' in col.lower()][0]
print(f"🔍 Date column identified: {date_col}")

# Convert to datetime
df[date_col] = pd.to_datetime(df[date_col])

# Convert Customer ID to integer then string
df[customer_col] = df[customer_col].astype(int).astype(str)

print("\n📋 Updated Data Types:")
print(df.dtypes)

# Step 7: Remove outliers using IQR method
def remove_outliers_iqr(data, column, multiplier=1.5):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - multiplier * IQR
    upper = Q3 + multiplier * IQR
    return data[(data[column] >= lower) & (data[column] <= upper)]

before = len(df)

# Remove quantity outliers
df = remove_outliers_iqr(df, quantity_col)

# Remove price outliers
df = remove_outliers_iqr(df, price_col)

after = len(df)

print(f"🔧 Removed {before - after:,} outlier rows")
print(f"📊 Final dataset: {after:,} rows")

# Preprocessing Summary
print("="*60)
print("✅ PREPROCESSING SUMMARY")
print("="*60)
print(f"📊 Original rows: {len(df_original):,}")
print(f"📊 Final rows: {len(df):,}")
print(f"📉 Rows removed: {len(df_original) - len(df):,} ({((len(df_original) - len(df))/len(df_original)*100):.1f}%)")
print(f"\n📋 Missing values remaining: {df.isnull().sum().sum()}")
print(f"\n📊 Final Shape: {df.shape}")

# Display cleaned data
df.head()

"""---
<a id='4'></a>
# 4️⃣ Module 2: Feature Engineering

### উদ্দেশ্য:
- TotalPrice তৈরি করা
- RFM Features তৈরি করা (Recency, Frequency, Monetary)
- Time-based features তৈরি করা
"""

# Step 1: Create TotalPrice
df['TotalPrice'] = df[quantity_col] * df[price_col]

print(f"💰 TotalPrice column created!")
print(f"   Min: £{df['TotalPrice'].min():.2f}")
print(f"   Max: £{df['TotalPrice'].max():.2f}")
print(f"   Mean: £{df['TotalPrice'].mean():.2f}")

# Step 2: Create Time-based Features
df['Year'] = df[date_col].dt.year
df['Month'] = df[date_col].dt.month
df['Day'] = df[date_col].dt.day
df['Hour'] = df[date_col].dt.hour
df['DayOfWeek'] = df[date_col].dt.dayofweek  # 0=Monday, 6=Sunday
df['DayName'] = df[date_col].dt.day_name()
df['IsWeekend'] = df['DayOfWeek'].isin([5, 6]).astype(int)

print("📅 Time-based features created:")
print("   - Year, Month, Day, Hour")
print("   - DayOfWeek, DayName, IsWeekend")

# Step 3: Create RFM Dataset
# Reference date (most recent date + 1 day)
reference_date = df[date_col].max() + pd.Timedelta(days=1)
print(f"📅 Reference Date for RFM: {reference_date.date()}")

# Calculate RFM
rfm = df.groupby(customer_col).agg({
    date_col: lambda x: (reference_date - x.max()).days,  # Recency
    invoice_col: 'nunique',  # Frequency
    'TotalPrice': 'sum'  # Monetary
}).reset_index()

# Rename columns
rfm.columns = ['CustomerID', 'Recency', 'Frequency', 'Monetary']

print(f"\n✅ RFM Dataset Created!")
print(f"📊 Shape: {rfm.shape}")
rfm.head(10)

# RFM Statistics
print("="*60)
print("📊 RFM STATISTICS")
print("="*60)
rfm.describe()

# Step 4: Create RFM Scores (1-5 scale)
# Lower recency is better, so we reverse the scoring
rfm['R_Score'] = pd.qcut(rfm['Recency'], q=5, labels=[5, 4, 3, 2, 1])
rfm['F_Score'] = pd.qcut(rfm['Frequency'].rank(method='first'), q=5, labels=[1, 2, 3, 4, 5])
rfm['M_Score'] = pd.qcut(rfm['Monetary'].rank(method='first'), q=5, labels=[1, 2, 3, 4, 5])

# Combined RFM Score
rfm['RFM_Score'] = rfm['R_Score'].astype(str) + rfm['F_Score'].astype(str) + rfm['M_Score'].astype(str)

# RFM Total Score (numeric)
rfm['RFM_Total'] = rfm['R_Score'].astype(int) + rfm['F_Score'].astype(int) + rfm['M_Score'].astype(int)

print("✅ RFM Scores created!")
rfm.head(10)

# Step 5: Create Customer Segments based on RFM
def segment_customer(row):
    r, f, m = int(row['R_Score']), int(row['F_Score']), int(row['M_Score'])

    if r >= 4 and f >= 4 and m >= 4:
        return 'Champions'
    elif r >= 3 and f >= 3 and m >= 3:
        return 'Loyal Customers'
    elif r >= 4 and f <= 2:
        return 'New Customers'
    elif r >= 3 and f >= 3 and m <= 2:
        return 'Promising'
    elif r <= 2 and f >= 3 and m >= 3:
        return 'At Risk'
    elif r <= 2 and f <= 2 and m <= 2:
        return 'Lost'
    elif r <= 2 and f >= 4:
        return 'Cannot Lose Them'
    else:
        return 'Others'

rfm['Segment'] = rfm.apply(segment_customer, axis=1)

# Segment distribution
print("👥 Customer Segments Distribution:")
print(rfm['Segment'].value_counts())

# Visualize Segment Distribution
plt.figure(figsize=(12, 6))

segment_counts = rfm['Segment'].value_counts()
colors = plt.cm.Set3(np.linspace(0, 1, len(segment_counts)))

plt.subplot(1, 2, 1)
plt.pie(segment_counts.values, labels=segment_counts.index, autopct='%1.1f%%', colors=colors)
plt.title('Customer Segments Distribution', fontsize=12, fontweight='bold')

plt.subplot(1, 2, 2)
segment_counts.plot(kind='bar', color=colors)
plt.title('Customer Segments Count', fontsize=12, fontweight='bold')
plt.xlabel('Segment')
plt.ylabel('Count')
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

# Step 6: Create Target Variable for Classification
# High-Value Customer: Monetary > median
median_monetary = rfm['Monetary'].median()
rfm['HighValue'] = (rfm['Monetary'] > median_monetary).astype(int)

print(f"💰 Median Monetary Value: £{median_monetary:.2f}")
print(f"\n🎯 Target Variable Distribution:")
print(rfm['HighValue'].value_counts())
print(f"\n📊 Ratio: {rfm['HighValue'].mean()*100:.1f}% High-Value Customers")

# Display final RFM dataset
print("="*60)
print("✅ FEATURE ENGINEERING COMPLETE")
print("="*60)
print(f"📊 Transaction Data Shape: {df.shape}")
print(f"📊 RFM Data Shape: {rfm.shape}")
print(f"\n📋 RFM Columns: {list(rfm.columns)}")

rfm.head()

"""---
<a id='5'></a>
# 5️⃣ Module 3: Exploratory Data Analysis (EDA)

### উদ্দেশ্য:
- Sales trends বিশ্লেষণ
- Top products ও customers খুঁজে বের করা
- Purchase patterns দেখা
"""

# 1. Monthly Sales Trend
monthly_sales = df.groupby([df[date_col].dt.to_period('M')])['TotalPrice'].sum().reset_index()
monthly_sales.columns = ['Month', 'Revenue']
monthly_sales['Month'] = monthly_sales['Month'].astype(str)

plt.figure(figsize=(14, 5))
plt.plot(monthly_sales['Month'], monthly_sales['Revenue'], marker='o', linewidth=2, markersize=6)
plt.fill_between(range(len(monthly_sales)), monthly_sales['Revenue'], alpha=0.3)
plt.title('📈 Monthly Revenue Trend', fontsize=14, fontweight='bold')
plt.xlabel('Month')
plt.ylabel('Revenue (£)')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# 2. Sales by Day of Week
daily_sales = df.groupby('DayName')['TotalPrice'].sum().reindex(
    ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
)

plt.figure(figsize=(10, 5))
colors = ['#3498db' if day not in ['Saturday', 'Sunday'] else '#e74c3c' for day in daily_sales.index]
plt.bar(daily_sales.index, daily_sales.values, color=colors)
plt.title('📅 Sales by Day of Week', fontsize=14, fontweight='bold')
plt.xlabel('Day')
plt.ylabel('Revenue (£)')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# 3. Sales by Hour
hourly_sales = df.groupby('Hour')['TotalPrice'].sum()

plt.figure(figsize=(12, 5))
plt.bar(hourly_sales.index, hourly_sales.values, color='#9b59b6')
plt.title('⏰ Sales by Hour of Day', fontsize=14, fontweight='bold')
plt.xlabel('Hour')
plt.ylabel('Revenue (£)')
plt.xticks(range(0, 24))
plt.tight_layout()
plt.show()

# 4. Top 10 Products by Revenue
desc_col = [col for col in df.columns if 'description' in col.lower()][0]

top_products_revenue = df.groupby(desc_col)['TotalPrice'].sum().nlargest(10)

plt.figure(figsize=(12, 6))
top_products_revenue.plot(kind='barh', color='#27ae60')
plt.title('🏆 Top 10 Products by Revenue', fontsize=14, fontweight='bold')
plt.xlabel('Revenue (£)')
plt.ylabel('Product')
plt.tight_layout()
plt.show()

# 5. Top 10 Products by Quantity Sold
top_products_qty = df.groupby(desc_col)[quantity_col].sum().nlargest(10)

plt.figure(figsize=(12, 6))
top_products_qty.plot(kind='barh', color='#e67e22')
plt.title('📦 Top 10 Products by Quantity Sold', fontsize=14, fontweight='bold')
plt.xlabel('Quantity')
plt.ylabel('Product')
plt.tight_layout()
plt.show()

# 6. Top 10 Countries by Revenue
country_col = [col for col in df.columns if 'country' in col.lower()][0]

top_countries = df.groupby(country_col)['TotalPrice'].sum().nlargest(10)

plt.figure(figsize=(10, 6))
top_countries.plot(kind='bar', color='#3498db')
plt.title('🌍 Top 10 Countries by Revenue', fontsize=14, fontweight='bold')
plt.xlabel('Country')
plt.ylabel('Revenue (£)')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# 7. Top 10 Customers by Revenue
top_customers = df.groupby(customer_col)['TotalPrice'].sum().nlargest(10)

plt.figure(figsize=(10, 6))
top_customers.plot(kind='bar', color='#9b59b6')
plt.title('👤 Top 10 Customers by Revenue', fontsize=14, fontweight='bold')
plt.xlabel('Customer ID')
plt.ylabel('Revenue (£)')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# 8. RFM Distribution
fig, axes = plt.subplots(1, 3, figsize=(15, 4))

# Recency Distribution
axes[0].hist(rfm['Recency'], bins=50, color='#e74c3c', edgecolor='black', alpha=0.7)
axes[0].set_title('Recency Distribution', fontsize=12, fontweight='bold')
axes[0].set_xlabel('Days')
axes[0].set_ylabel('Count')

# Frequency Distribution
axes[1].hist(rfm['Frequency'], bins=50, color='#2ecc71', edgecolor='black', alpha=0.7)
axes[1].set_title('Frequency Distribution', fontsize=12, fontweight='bold')
axes[1].set_xlabel('Number of Purchases')
axes[1].set_ylabel('Count')

# Monetary Distribution
axes[2].hist(rfm['Monetary'], bins=50, color='#3498db', edgecolor='black', alpha=0.7)
axes[2].set_title('Monetary Distribution', fontsize=12, fontweight='bold')
axes[2].set_xlabel('Total Spend (£)')
axes[2].set_ylabel('Count')

plt.tight_layout()
plt.show()

# 10. Weekend vs Weekday Sales
weekend_sales = df.groupby('IsWeekend')['TotalPrice'].sum()

plt.figure(figsize=(8, 5))
labels = ['Weekday', 'Weekend']
colors = ['#3498db', '#e74c3c']
plt.pie(weekend_sales.values, labels=labels, autopct='%1.1f%%', colors=colors, explode=[0, 0.05])
plt.title('📊 Weekday vs Weekend Sales', fontsize=14, fontweight='bold')
plt.show()

# EDA Summary
print("="*60)
print("📊 EDA KEY INSIGHTS")
print("="*60)
print(f"📈 Total Revenue: £{df['TotalPrice'].sum():,.2f}")
print(f"📦 Total Transactions: {df[invoice_col].nunique():,}")
print(f"👥 Unique Customers: {df[customer_col].nunique():,}")
print(f"🛍️ Unique Products: {df[desc_col].nunique():,}")
print(f"🌍 Countries: {df[country_col].nunique()}")
print(f"\n💰 Average Order Value: £{df.groupby(invoice_col)['TotalPrice'].sum().mean():,.2f}")
print(f"📅 Date Range: {df[date_col].min().date()} to {df[date_col].max().date()}")

"""---
<a id='6'></a>
# 6️⃣ Module 4: Dimensionality Reduction

### উদ্দেশ্য:
- PCA দিয়ে variance retain করে features কমানো
- t-SNE দিয়ে 2D visualization
- UMAP দিয়ে cluster visualization
"""

# Prepare data for dimensionality reduction
rfm_features = rfm[['Recency', 'Frequency', 'Monetary']].copy()

# Standardize the features
scaler = StandardScaler()
rfm_scaled = scaler.fit_transform(rfm_features)

print("✅ Data scaled for dimensionality reduction")
print(f"📊 Shape: {rfm_scaled.shape}")

# 1. PCA (Principal Component Analysis)
pca = PCA()
pca_result = pca.fit_transform(rfm_scaled)

# Explained Variance
explained_variance = pca.explained_variance_ratio_
cumulative_variance = np.cumsum(explained_variance)

print("📊 PCA Explained Variance:")
for i, (ev, cv) in enumerate(zip(explained_variance, cumulative_variance)):
    print(f"   PC{i+1}: {ev*100:.2f}% (Cumulative: {cv*100:.2f}%)")

# Visualize PCA Explained Variance
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Bar chart
axes[0].bar(range(1, len(explained_variance)+1), explained_variance*100, color='#3498db', alpha=0.7)
axes[0].plot(range(1, len(cumulative_variance)+1), cumulative_variance*100, 'ro-', linewidth=2)
axes[0].set_xlabel('Principal Component')
axes[0].set_ylabel('Explained Variance (%)')
axes[0].set_title('PCA Explained Variance', fontsize=12, fontweight='bold')
axes[0].axhline(y=80, color='g', linestyle='--', label='80% threshold')
axes[0].legend()

# 2D Scatter Plot
scatter = axes[1].scatter(pca_result[:, 0], pca_result[:, 1], c=rfm['HighValue'], cmap='coolwarm', alpha=0.6)
axes[1].set_xlabel(f'PC1 ({explained_variance[0]*100:.1f}%)')
axes[1].set_ylabel(f'PC2 ({explained_variance[1]*100:.1f}%)')
axes[1].set_title('PCA 2D Projection', fontsize=12, fontweight='bold')
plt.colorbar(scatter, ax=axes[1], label='High Value')

plt.tight_layout()
plt.show()

# 2. t-SNE (t-Distributed Stochastic Neighbor Embedding)
print("⏳ Running t-SNE (this may take a moment)...")

# Sample if data is too large
sample_size = min(5000, len(rfm_scaled))
np.random.seed(42)
sample_idx = np.random.choice(len(rfm_scaled), sample_size, replace=False)

tsne = TSNE(n_components=2, random_state=42, perplexity=30, n_iter=1000)
tsne_result = tsne.fit_transform(rfm_scaled[sample_idx])

print("✅ t-SNE completed!")

# Visualize t-SNE
plt.figure(figsize=(10, 8))
scatter = plt.scatter(tsne_result[:, 0], tsne_result[:, 1],
                      c=rfm['HighValue'].iloc[sample_idx], cmap='coolwarm', alpha=0.6, s=20)
plt.colorbar(scatter, label='High Value')
plt.title('t-SNE 2D Visualization', fontsize=14, fontweight='bold')
plt.xlabel('t-SNE 1')
plt.ylabel('t-SNE 2')
plt.tight_layout()
plt.show()

# 3. UMAP (Uniform Manifold Approximation and Projection)
print("⏳ Running UMAP...")

umap_model = umap.UMAP(n_components=2, random_state=42, n_neighbors=15, min_dist=0.1)
umap_result = umap_model.fit_transform(rfm_scaled[sample_idx])

print("✅ UMAP completed!")

# Visualize UMAP
plt.figure(figsize=(10, 8))
scatter = plt.scatter(umap_result[:, 0], umap_result[:, 1],
                      c=rfm['HighValue'].iloc[sample_idx], cmap='coolwarm', alpha=0.6, s=20)
plt.colorbar(scatter, label='High Value')
plt.title('UMAP 2D Visualization', fontsize=14, fontweight='bold')
plt.xlabel('UMAP 1')
plt.ylabel('UMAP 2')
plt.tight_layout()
plt.show()

# Compare all three methods
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# PCA
axes[0].scatter(pca_result[sample_idx, 0], pca_result[sample_idx, 1],
                c=rfm['HighValue'].iloc[sample_idx], cmap='coolwarm', alpha=0.6, s=15)
axes[0].set_title('PCA', fontsize=12, fontweight='bold')
axes[0].set_xlabel('PC1')
axes[0].set_ylabel('PC2')

# t-SNE
axes[1].scatter(tsne_result[:, 0], tsne_result[:, 1],
                c=rfm['HighValue'].iloc[sample_idx], cmap='coolwarm', alpha=0.6, s=15)
axes[1].set_title('t-SNE', fontsize=12, fontweight='bold')
axes[1].set_xlabel('t-SNE 1')
axes[1].set_ylabel('t-SNE 2')

# UMAP
scatter = axes[2].scatter(umap_result[:, 0], umap_result[:, 1],
                          c=rfm['HighValue'].iloc[sample_idx], cmap='coolwarm', alpha=0.6, s=15)
axes[2].set_title('UMAP', fontsize=12, fontweight='bold')
axes[2].set_xlabel('UMAP 1')
axes[2].set_ylabel('UMAP 2')

plt.colorbar(scatter, ax=axes, label='High Value', shrink=0.8)
plt.suptitle('Dimensionality Reduction Comparison', fontsize=14, fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()

"""---
<a id='7'></a>
# 7️⃣ Module 5: Association Rule Mining (FP-Growth)

### উদ্দেশ্য:
- কোন products একসাথে বিক্রি হয় সেটা বের করা
- FP-Growth algorithm ব্যবহার করা
- Support, Confidence, Lift calculate করা
"""

# Prepare basket data for association rules
# Group products by Invoice

print("⏳ Preparing basket data for FP-Growth...")

# Create basket: each row is a transaction with list of products
basket = df.groupby([invoice_col, desc_col])[quantity_col].sum().unstack().reset_index().fillna(0).set_index(invoice_col)

print(f"📊 Basket Shape: {basket.shape}")
print(f"   Transactions: {basket.shape[0]:,}")
print(f"   Unique Products: {basket.shape[1]:,}")

# Convert to binary (0/1) - purchased or not
def encode_units(x):
    if x <= 0:
        return 0
    if x >= 1:
        return 1

basket_encoded = basket.applymap(encode_units)

print("✅ Basket encoded to binary format")
basket_encoded.head()

# Filter for UK only (largest market) to reduce computation
# Or use full data if needed

# Sample if too large
if basket_encoded.shape[0] > 10000:
    print("⚠️ Large dataset - sampling 10,000 transactions for faster processing")
    basket_sample = basket_encoded.sample(n=10000, random_state=42)
else:
    basket_sample = basket_encoded

print(f"📊 Using {basket_sample.shape[0]:,} transactions for FP-Growth")

# Apply FP-Growth Algorithm
print("⏳ Running FP-Growth algorithm...")

# Find frequent itemsets with minimum support of 1%
frequent_itemsets = fpgrowth(basket_sample, min_support=0.01, use_colnames=True)

print(f"✅ Found {len(frequent_itemsets)} frequent itemsets")
frequent_itemsets.head(10)

# Generate Association Rules
print("⏳ Generating association rules...")

rules = association_rules(frequent_itemsets, metric='lift', min_threshold=1.0)

# Filter strong rules
strong_rules = rules[(rules['confidence'] >= 0.3) & (rules['lift'] >= 1.5)]

print(f"✅ Generated {len(rules)} rules")
print(f"✅ Strong rules (confidence >= 0.3, lift >= 1.5): {len(strong_rules)}")

# Display top rules by lift
print("="*60)
print("🔗 TOP 20 ASSOCIATION RULES (by Lift)")
print("="*60)

top_rules = rules.nlargest(20, 'lift')[['antecedents', 'consequents', 'support', 'confidence', 'lift']]
top_rules

# Visualize Association Rules
plt.figure(figsize=(12, 6))

# Scatter plot: Support vs Confidence, colored by Lift
scatter = plt.scatter(rules['support'], rules['confidence'],
                      c=rules['lift'], cmap='viridis', alpha=0.6, s=50)
plt.colorbar(scatter, label='Lift')
plt.xlabel('Support')
plt.ylabel('Confidence')
plt.title('🔗 Association Rules: Support vs Confidence (colored by Lift)', fontsize=12, fontweight='bold')
plt.tight_layout()
plt.show()

# Top 10 rules visualization
top10_rules = rules.nlargest(10, 'lift').copy()
top10_rules['rule'] = top10_rules['antecedents'].astype(str) + ' → ' + top10_rules['consequents'].astype(str)
top10_rules['rule'] = top10_rules['rule'].str.replace('frozenset', '').str.replace('{', '').str.replace('}', '')
top10_rules['rule'] = top10_rules['rule'].str[:50]  # Truncate for display

plt.figure(figsize=(12, 6))
plt.barh(range(len(top10_rules)), top10_rules['lift'], color='#9b59b6')
plt.yticks(range(len(top10_rules)), top10_rules['rule'])
plt.xlabel('Lift')
plt.title('🏆 Top 10 Association Rules by Lift', fontsize=12, fontweight='bold')
plt.tight_layout()
plt.show()

# Association Rules Summary
print("="*60)
print("📊 ASSOCIATION RULES SUMMARY")
print("="*60)
print(f"📦 Total Transactions Analyzed: {basket_sample.shape[0]:,}")
print(f"🛍️ Unique Products: {basket_sample.shape[1]:,}")
print(f"🔗 Frequent Itemsets Found: {len(frequent_itemsets)}")
print(f"📋 Total Rules Generated: {len(rules)}")
print(f"✅ Strong Rules: {len(strong_rules)}")
print(f"\n📈 Average Confidence: {rules['confidence'].mean():.2%}")
print(f"📈 Average Lift: {rules['lift'].mean():.2f}")
print(f"📈 Max Lift: {rules['lift'].max():.2f}")

"""---
<a id='8'></a>
# 8️⃣ Module 6: Customer Segmentation (Clustering)

### উদ্দেশ্য:
- K-Means clustering
- DBSCAN clustering
- Hierarchical clustering
- Optimal cluster সংখ্যা বের করা
"""

# Prepare data for clustering
clustering_features = rfm[['Recency', 'Frequency', 'Monetary']].copy()

# Scale the features
scaler = StandardScaler()
clustering_scaled = scaler.fit_transform(clustering_features)

print("✅ Data prepared for clustering")
print(f"📊 Shape: {clustering_scaled.shape}")

# 1. Find Optimal K using Elbow Method
inertias = []
silhouette_scores = []
K_range = range(2, 11)

print("⏳ Finding optimal K...")

for k in K_range:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(clustering_scaled)
    inertias.append(kmeans.inertia_)
    silhouette_scores.append(silhouette_score(clustering_scaled, kmeans.labels_))
    print(f"   K={k}: Inertia={kmeans.inertia_:.2f}, Silhouette={silhouette_scores[-1]:.4f}")

# Visualize Elbow and Silhouette
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Elbow Method
axes[0].plot(K_range, inertias, 'bo-', linewidth=2, markersize=8)
axes[0].set_xlabel('Number of Clusters (K)')
axes[0].set_ylabel('Inertia')
axes[0].set_title('Elbow Method', fontsize=12, fontweight='bold')

# Silhouette Score
axes[1].plot(K_range, silhouette_scores, 'go-', linewidth=2, markersize=8)
axes[1].set_xlabel('Number of Clusters (K)')
axes[1].set_ylabel('Silhouette Score')
axes[1].set_title('Silhouette Score Method', fontsize=12, fontweight='bold')

# Mark optimal K
optimal_k = K_range[np.argmax(silhouette_scores)]
axes[1].axvline(x=optimal_k, color='r', linestyle='--', label=f'Optimal K={optimal_k}')
axes[1].legend()

plt.tight_layout()
plt.show()

print(f"\n✅ Optimal K based on Silhouette Score: {optimal_k}")

# 2. Apply K-Means with optimal K
kmeans = KMeans(n_clusters=optimal_k, random_state=42, n_init=10)
rfm['KMeans_Cluster'] = kmeans.fit_predict(clustering_scaled)

print(f"✅ K-Means Clustering Complete (K={optimal_k})")
print(f"\n📊 Cluster Distribution:")
print(rfm['KMeans_Cluster'].value_counts().sort_index())

# Visualize K-Means Clusters
fig = plt.figure(figsize=(15, 5))

# 2D visualization using PCA
pca_2d = PCA(n_components=2)
pca_result = pca_2d.fit_transform(clustering_scaled)

ax1 = fig.add_subplot(131)
scatter = ax1.scatter(pca_result[:, 0], pca_result[:, 1], c=rfm['KMeans_Cluster'], cmap='viridis', alpha=0.6)
ax1.set_title('K-Means Clusters (PCA View)', fontsize=12, fontweight='bold')
ax1.set_xlabel('PC1')
ax1.set_ylabel('PC2')
plt.colorbar(scatter, ax=ax1)

# Recency vs Monetary
ax2 = fig.add_subplot(132)
scatter = ax2.scatter(rfm['Recency'], rfm['Monetary'], c=rfm['KMeans_Cluster'], cmap='viridis', alpha=0.6)
ax2.set_title('Recency vs Monetary', fontsize=12, fontweight='bold')
ax2.set_xlabel('Recency')
ax2.set_ylabel('Monetary')
plt.colorbar(scatter, ax=ax2)

# Frequency vs Monetary
ax3 = fig.add_subplot(133)
scatter = ax3.scatter(rfm['Frequency'], rfm['Monetary'], c=rfm['KMeans_Cluster'], cmap='viridis', alpha=0.6)
ax3.set_title('Frequency vs Monetary', fontsize=12, fontweight='bold')
ax3.set_xlabel('Frequency')
ax3.set_ylabel('Monetary')
plt.colorbar(scatter, ax=ax3)

plt.tight_layout()
plt.show()

# Cluster Analysis - Mean values
cluster_analysis = rfm.groupby('KMeans_Cluster')[['Recency', 'Frequency', 'Monetary']].mean().round(2)
cluster_analysis['Count'] = rfm['KMeans_Cluster'].value_counts().sort_index()

print("="*60)
print("📊 K-MEANS CLUSTER PROFILES")
print("="*60)
cluster_analysis

# 3. DBSCAN Clustering
print("⏳ Running DBSCAN...")

dbscan = DBSCAN(eps=0.5, min_samples=10)
rfm['DBSCAN_Cluster'] = dbscan.fit_predict(clustering_scaled)

n_clusters_dbscan = len(set(rfm['DBSCAN_Cluster'])) - (1 if -1 in rfm['DBSCAN_Cluster'].values else 0)
n_noise = (rfm['DBSCAN_Cluster'] == -1).sum()

print(f"✅ DBSCAN Complete")
print(f"   Clusters found: {n_clusters_dbscan}")
print(f"   Noise points: {n_noise} ({n_noise/len(rfm)*100:.1f}%)")

# Visualize DBSCAN
plt.figure(figsize=(10, 6))
scatter = plt.scatter(pca_result[:, 0], pca_result[:, 1], c=rfm['DBSCAN_Cluster'], cmap='viridis', alpha=0.6)
plt.colorbar(scatter)
plt.title('DBSCAN Clusters (PCA View)', fontsize=12, fontweight='bold')
plt.xlabel('PC1')
plt.ylabel('PC2')
plt.tight_layout()
plt.show()

# 4. Hierarchical Clustering
print("⏳ Running Hierarchical Clustering...")

# Sample for dendrogram (too slow with full data)
sample_size = min(1000, len(clustering_scaled))
sample_idx = np.random.choice(len(clustering_scaled), sample_size, replace=False)
sample_data = clustering_scaled[sample_idx]

# Create linkage matrix
linkage_matrix = linkage(sample_data, method='ward')

# Plot dendrogram
plt.figure(figsize=(14, 6))
dendrogram(linkage_matrix, truncate_mode='level', p=5)
plt.title('Hierarchical Clustering Dendrogram', fontsize=14, fontweight='bold')
plt.xlabel('Sample Index')
plt.ylabel('Distance')
plt.tight_layout()
plt.show()

# Apply Agglomerative Clustering
agg_clustering = AgglomerativeClustering(n_clusters=optimal_k)
rfm['Hierarchical_Cluster'] = agg_clustering.fit_predict(clustering_scaled)

print(f"✅ Hierarchical Clustering Complete (K={optimal_k})")
print(f"\n📊 Cluster Distribution:")
print(rfm['Hierarchical_Cluster'].value_counts().sort_index())

# Compare Clustering Methods
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# K-Means
axes[0].scatter(pca_result[:, 0], pca_result[:, 1], c=rfm['KMeans_Cluster'], cmap='viridis', alpha=0.6, s=15)
axes[0].set_title(f'K-Means (K={optimal_k})', fontsize=12, fontweight='bold')
axes[0].set_xlabel('PC1')
axes[0].set_ylabel('PC2')

# DBSCAN
axes[1].scatter(pca_result[:, 0], pca_result[:, 1], c=rfm['DBSCAN_Cluster'], cmap='viridis', alpha=0.6, s=15)
axes[1].set_title(f'DBSCAN', fontsize=12, fontweight='bold')
axes[1].set_xlabel('PC1')
axes[1].set_ylabel('PC2')

# Hierarchical
scatter = axes[2].scatter(pca_result[:, 0], pca_result[:, 1], c=rfm['Hierarchical_Cluster'], cmap='viridis', alpha=0.6, s=15)
axes[2].set_title(f'Hierarchical (K={optimal_k})', fontsize=12, fontweight='bold')
axes[2].set_xlabel('PC1')
axes[2].set_ylabel('PC2')

plt.suptitle('Clustering Methods Comparison', fontsize=14, fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()

# Clustering Summary
print("="*60)
print("📊 CLUSTERING SUMMARY")
print("="*60)
print(f"\n1️⃣ K-Means:")
print(f"   Optimal K: {optimal_k}")
print(f"   Silhouette Score: {silhouette_score(clustering_scaled, rfm['KMeans_Cluster']):.4f}")

print(f"\n2️⃣ DBSCAN:")
print(f"   Clusters: {n_clusters_dbscan}")
print(f"   Noise Points: {n_noise}")

print(f"\n3️⃣ Hierarchical:")
print(f"   Clusters: {optimal_k}")
print(f"   Silhouette Score: {silhouette_score(clustering_scaled, rfm['Hierarchical_Cluster']):.4f}")

"""---
<a id='9'></a>
# 9️⃣ Module 7: Classification Models

### উদ্দেশ্য:
- High-Value Customer predict করা
- Multiple classification models train করা
- Model performance তুলনা করা
"""

# Prepare data for classification
X = rfm[['Recency', 'Frequency', 'Monetary']].copy()
y = rfm['HighValue'].copy()

# Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split data
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42, stratify=y)

print("✅ Data prepared for classification")
print(f"📊 Training set: {X_train.shape[0]} samples")
print(f"📊 Test set: {X_test.shape[0]} samples")
print(f"\n🎯 Target Distribution:")
print(f"   Train - Class 0: {(y_train==0).sum()}, Class 1: {(y_train==1).sum()}")
print(f"   Test - Class 0: {(y_test==0).sum()}, Class 1: {(y_test==1).sum()}")

# Define models
models = {
    'Logistic Regression': LogisticRegression(random_state=42, max_iter=1000),
    'Decision Tree': DecisionTreeClassifier(random_state=42, max_depth=10),
    'Random Forest': RandomForestClassifier(random_state=42, n_estimators=100),
    'XGBoost': XGBClassifier(random_state=42, n_estimators=100, use_label_encoder=False, eval_metric='logloss'),
    'SVM': SVC(random_state=42, probability=True),
    'Gradient Boosting': GradientBoostingClassifier(random_state=42, n_estimators=100)
}

print(f"📋 Models to train: {list(models.keys())}")

# Train and evaluate all models
results = []

print("="*60)
print("🚀 TRAINING MODELS")
print("="*60)

for name, model in models.items():
    print(f"\n⏳ Training {name}...")

    # Train
    model.fit(X_train, y_train)

    # Predict
    y_pred = model.predict(X_test)
    y_pred_proba = model.predict_proba(X_test)[:, 1]

    # Metrics
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    roc_auc = roc_auc_score(y_test, y_pred_proba)

    results.append({
        'Model': name,
        'Accuracy': accuracy,
        'Precision': precision,
        'Recall': recall,
        'F1-Score': f1,
        'ROC-AUC': roc_auc
    })

    print(f"   ✅ Accuracy: {accuracy:.4f} | F1: {f1:.4f} | ROC-AUC: {roc_auc:.4f}")

# Create results DataFrame
results_df = pd.DataFrame(results).sort_values('F1-Score', ascending=False)
results_df = results_df.round(4)

# Display Results
print("="*60)
print("📊 MODEL COMPARISON RESULTS")
print("="*60)
results_df

# Visualize Model Comparison
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Metrics comparison
metrics = ['Accuracy', 'Precision', 'Recall', 'F1-Score', 'ROC-AUC']
x = np.arange(len(results_df))
width = 0.15

for i, metric in enumerate(metrics):
    axes[0].bar(x + i*width, results_df[metric], width, label=metric)

axes[0].set_xlabel('Model')
axes[0].set_ylabel('Score')
axes[0].set_title('Model Performance Comparison', fontsize=12, fontweight='bold')
axes[0].set_xticks(x + width * 2)
axes[0].set_xticklabels(results_df['Model'], rotation=45, ha='right')
axes[0].legend(loc='lower right')
axes[0].set_ylim(0, 1.1)

# ROC Curves
for name, model in models.items():
    y_pred_proba = model.predict_proba(X_test)[:, 1]
    fpr, tpr, _ = roc_curve(y_test, y_pred_proba)
    roc_auc = roc_auc_score(y_test, y_pred_proba)
    axes[1].plot(fpr, tpr, label=f'{name} (AUC = {roc_auc:.3f})')

axes[1].plot([0, 1], [0, 1], 'k--', label='Random')
axes[1].set_xlabel('False Positive Rate')
axes[1].set_ylabel('True Positive Rate')
axes[1].set_title('ROC Curves', fontsize=12, fontweight='bold')
axes[1].legend(loc='lower right', fontsize=8)

plt.tight_layout()
plt.show()

# Best Model - Confusion Matrix
best_model_name = results_df.iloc[0]['Model']
best_model = models[best_model_name]
y_pred_best = best_model.predict(X_test)

plt.figure(figsize=(8, 6))
cm = confusion_matrix(y_test, y_pred_best)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Low Value', 'High Value'],
            yticklabels=['Low Value', 'High Value'])
plt.title(f'Confusion Matrix - {best_model_name}', fontsize=12, fontweight='bold')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.tight_layout()
plt.show()

# Classification Report
print(f"\n📊 Classification Report - {best_model_name}")
print("="*50)
print(classification_report(y_test, y_pred_best, target_names=['Low Value', 'High Value']))

# Feature Importance (for tree-based models)
if hasattr(models['Random Forest'], 'feature_importances_'):
    feature_names = ['Recency', 'Frequency', 'Monetary']
    importances = models['Random Forest'].feature_importances_

    plt.figure(figsize=(8, 5))
    plt.barh(feature_names, importances, color='#3498db')
    plt.xlabel('Importance')
    plt.title('Feature Importance (Random Forest)', fontsize=12, fontweight='bold')
    plt.tight_layout()
    plt.show()

"""---
<a id='10'></a>
# 🔟 Module 8: Ensemble Learning

### উদ্দেশ্য:
- Voting Classifier
- Stacking Classifier
- Ensemble methods এর performance তুলনা
"""

# 1. Voting Classifier (Hard Voting)
print("⏳ Training Voting Classifier (Hard)...")

voting_hard = VotingClassifier(
    estimators=[
        ('lr', LogisticRegression(random_state=42, max_iter=1000)),
        ('rf', RandomForestClassifier(random_state=42, n_estimators=100)),
        ('xgb', XGBClassifier(random_state=42, n_estimators=100, use_label_encoder=False, eval_metric='logloss'))
    ],
    voting='hard'
)

voting_hard.fit(X_train, y_train)
y_pred_voting_hard = voting_hard.predict(X_test)

print(f"✅ Accuracy: {accuracy_score(y_test, y_pred_voting_hard):.4f}")
print(f"✅ F1-Score: {f1_score(y_test, y_pred_voting_hard):.4f}")

# 2. Voting Classifier (Soft Voting)
print("⏳ Training Voting Classifier (Soft)...")

voting_soft = VotingClassifier(
    estimators=[
        ('lr', LogisticRegression(random_state=42, max_iter=1000)),
        ('rf', RandomForestClassifier(random_state=42, n_estimators=100)),
        ('xgb', XGBClassifier(random_state=42, n_estimators=100, use_label_encoder=False, eval_metric='logloss'))
    ],
    voting='soft'
)

voting_soft.fit(X_train, y_train)
y_pred_voting_soft = voting_soft.predict(X_test)
y_pred_proba_voting = voting_soft.predict_proba(X_test)[:, 1]

print(f"✅ Accuracy: {accuracy_score(y_test, y_pred_voting_soft):.4f}")
print(f"✅ F1-Score: {f1_score(y_test, y_pred_voting_soft):.4f}")
print(f"✅ ROC-AUC: {roc_auc_score(y_test, y_pred_proba_voting):.4f}")

# 3. Stacking Classifier
print("⏳ Training Stacking Classifier...")

stacking = StackingClassifier(
    estimators=[
        ('rf', RandomForestClassifier(random_state=42, n_estimators=100)),
        ('xgb', XGBClassifier(random_state=42, n_estimators=100, use_label_encoder=False, eval_metric='logloss')),
        ('svm', SVC(random_state=42, probability=True))
    ],
    final_estimator=LogisticRegression(random_state=42, max_iter=1000),
    cv=5
)

stacking.fit(X_train, y_train)
y_pred_stacking = stacking.predict(X_test)
y_pred_proba_stacking = stacking.predict_proba(X_test)[:, 1]

print(f"✅ Accuracy: {accuracy_score(y_test, y_pred_stacking):.4f}")
print(f"✅ F1-Score: {f1_score(y_test, y_pred_stacking):.4f}")
print(f"✅ ROC-AUC: {roc_auc_score(y_test, y_pred_proba_stacking):.4f}")

# 4. AdaBoost
print("⏳ Training AdaBoost...")

adaboost = AdaBoostClassifier(random_state=42, n_estimators=100)
adaboost.fit(X_train, y_train)
y_pred_ada = adaboost.predict(X_test)
y_pred_proba_ada = adaboost.predict_proba(X_test)[:, 1]

print(f"✅ Accuracy: {accuracy_score(y_test, y_pred_ada):.4f}")
print(f"✅ F1-Score: {f1_score(y_test, y_pred_ada):.4f}")
print(f"✅ ROC-AUC: {roc_auc_score(y_test, y_pred_proba_ada):.4f}")

# Ensemble Comparison
ensemble_results = [
    {'Model': 'Voting (Hard)', 'Accuracy': accuracy_score(y_test, y_pred_voting_hard),
     'F1-Score': f1_score(y_test, y_pred_voting_hard), 'ROC-AUC': '-'},
    {'Model': 'Voting (Soft)', 'Accuracy': accuracy_score(y_test, y_pred_voting_soft),
     'F1-Score': f1_score(y_test, y_pred_voting_soft), 'ROC-AUC': roc_auc_score(y_test, y_pred_proba_voting)},
    {'Model': 'Stacking', 'Accuracy': accuracy_score(y_test, y_pred_stacking),
     'F1-Score': f1_score(y_test, y_pred_stacking), 'ROC-AUC': roc_auc_score(y_test, y_pred_proba_stacking)},
    {'Model': 'AdaBoost', 'Accuracy': accuracy_score(y_test, y_pred_ada),
     'F1-Score': f1_score(y_test, y_pred_ada), 'ROC-AUC': roc_auc_score(y_test, y_pred_proba_ada)}
]

ensemble_df = pd.DataFrame(ensemble_results)

print("="*60)
print("📊 ENSEMBLE METHODS COMPARISON")
print("="*60)
ensemble_df

# Visualize Ensemble Comparison
fig, ax = plt.subplots(figsize=(10, 6))

x = np.arange(len(ensemble_df))
width = 0.25

ax.bar(x - width, ensemble_df['Accuracy'], width, label='Accuracy', color='#3498db')
ax.bar(x, ensemble_df['F1-Score'], width, label='F1-Score', color='#2ecc71')

ax.set_xlabel('Ensemble Method')
ax.set_ylabel('Score')
ax.set_title('Ensemble Methods Performance', fontsize=12, fontweight='bold')
ax.set_xticks(x)
ax.set_xticklabels(ensemble_df['Model'])
ax.legend()
ax.set_ylim(0, 1.1)

plt.tight_layout()
plt.show()

"""---
<a id='11'></a>
# 1️⃣1️⃣ Module 9: Anomaly Detection

### উদ্দেশ্য:
- অস্বাভাবিক transactions খুঁজে বের করা
- Isolation Forest, LOF, One-Class SVM ব্যবহার করা
"""

# Prepare data for anomaly detection
anomaly_features = rfm[['Recency', 'Frequency', 'Monetary']].copy()

# Scale features
scaler = StandardScaler()
anomaly_scaled = scaler.fit_transform(anomaly_features)

print("✅ Data prepared for anomaly detection")
print(f"📊 Shape: {anomaly_scaled.shape}")

# 1. Isolation Forest
print("⏳ Running Isolation Forest...")

iso_forest = IsolationForest(contamination=0.05, random_state=42, n_estimators=100)
rfm['Anomaly_IF'] = iso_forest.fit_predict(anomaly_scaled)
rfm['Anomaly_IF'] = rfm['Anomaly_IF'].map({1: 0, -1: 1})  # 0 = Normal, 1 = Anomaly

n_anomalies_if = rfm['Anomaly_IF'].sum()
print(f"✅ Isolation Forest - Anomalies detected: {n_anomalies_if} ({n_anomalies_if/len(rfm)*100:.2f}%)")

# 2. Local Outlier Factor (LOF)
print("⏳ Running Local Outlier Factor...")

lof = LocalOutlierFactor(n_neighbors=20, contamination=0.05)
rfm['Anomaly_LOF'] = lof.fit_predict(anomaly_scaled)
rfm['Anomaly_LOF'] = rfm['Anomaly_LOF'].map({1: 0, -1: 1})

n_anomalies_lof = rfm['Anomaly_LOF'].sum()
print(f"✅ LOF - Anomalies detected: {n_anomalies_lof} ({n_anomalies_lof/len(rfm)*100:.2f}%)")

# 3. One-Class SVM
print("⏳ Running One-Class SVM...")

# Sample if too large (One-Class SVM is slow)
if len(anomaly_scaled) > 5000:
    print("   (Using sample for faster processing)")
    sample_idx = np.random.choice(len(anomaly_scaled), 5000, replace=False)
    oc_svm = OneClassSVM(nu=0.05, kernel='rbf', gamma='auto')
    oc_svm.fit(anomaly_scaled[sample_idx])
    rfm['Anomaly_SVM'] = oc_svm.predict(anomaly_scaled)
else:
    oc_svm = OneClassSVM(nu=0.05, kernel='rbf', gamma='auto')
    rfm['Anomaly_SVM'] = oc_svm.fit_predict(anomaly_scaled)

rfm['Anomaly_SVM'] = rfm['Anomaly_SVM'].map({1: 0, -1: 1})

n_anomalies_svm = rfm['Anomaly_SVM'].sum()
print(f"✅ One-Class SVM - Anomalies detected: {n_anomalies_svm} ({n_anomalies_svm/len(rfm)*100:.2f}%)")

# Combined Anomaly Score (majority voting)
rfm['Anomaly_Combined'] = ((rfm['Anomaly_IF'] + rfm['Anomaly_LOF'] + rfm['Anomaly_SVM']) >= 2).astype(int)

n_anomalies_combined = rfm['Anomaly_Combined'].sum()
print(f"\n📊 Combined Anomalies (2+ methods agree): {n_anomalies_combined} ({n_anomalies_combined/len(rfm)*100:.2f}%)")

# Visualize Anomalies
fig, axes = plt.subplots(2, 2, figsize=(14, 12))

# Isolation Forest
axes[0, 0].scatter(rfm['Frequency'], rfm['Monetary'], c=rfm['Anomaly_IF'], cmap='coolwarm', alpha=0.6, s=20)
axes[0, 0].set_xlabel('Frequency')
axes[0, 0].set_ylabel('Monetary')
axes[0, 0].set_title(f'Isolation Forest ({n_anomalies_if} anomalies)', fontsize=12, fontweight='bold')

# LOF
axes[0, 1].scatter(rfm['Frequency'], rfm['Monetary'], c=rfm['Anomaly_LOF'], cmap='coolwarm', alpha=0.6, s=20)
axes[0, 1].set_xlabel('Frequency')
axes[0, 1].set_ylabel('Monetary')
axes[0, 1].set_title(f'Local Outlier Factor ({n_anomalies_lof} anomalies)', fontsize=12, fontweight='bold')

# One-Class SVM
axes[1, 0].scatter(rfm['Frequency'], rfm['Monetary'], c=rfm['Anomaly_SVM'], cmap='coolwarm', alpha=0.6, s=20)
axes[1, 0].set_xlabel('Frequency')
axes[1, 0].set_ylabel('Monetary')
axes[1, 0].set_title(f'One-Class SVM ({n_anomalies_svm} anomalies)', fontsize=12, fontweight='bold')

# Combined
scatter = axes[1, 1].scatter(rfm['Frequency'], rfm['Monetary'], c=rfm['Anomaly_Combined'], cmap='coolwarm', alpha=0.6, s=20)
axes[1, 1].set_xlabel('Frequency')
axes[1, 1].set_ylabel('Monetary')
axes[1, 1].set_title(f'Combined (Majority Vote) ({n_anomalies_combined} anomalies)', fontsize=12, fontweight='bold')

plt.tight_layout()
plt.show()

# Display Anomalous Customers
anomalies = rfm[rfm['Anomaly_Combined'] == 1][['CustomerID', 'Recency', 'Frequency', 'Monetary', 'Segment']]

print("="*60)
print("🚨 ANOMALOUS CUSTOMERS (Top 20)")
print("="*60)
anomalies.head(20)

# Anomaly Statistics
print("\n📊 Anomaly vs Normal Customer Comparison:")
comparison = rfm.groupby('Anomaly_Combined')[['Recency', 'Frequency', 'Monetary']].mean().round(2)
comparison.index = ['Normal', 'Anomaly']
comparison

# Anomaly Detection Summary
print("="*60)
print("📊 ANOMALY DETECTION SUMMARY")
print("="*60)
print(f"\n1️⃣ Isolation Forest: {n_anomalies_if} anomalies ({n_anomalies_if/len(rfm)*100:.2f}%)")
print(f"2️⃣ Local Outlier Factor: {n_anomalies_lof} anomalies ({n_anomalies_lof/len(rfm)*100:.2f}%)")
print(f"3️⃣ One-Class SVM: {n_anomalies_svm} anomalies ({n_anomalies_svm/len(rfm)*100:.2f}%)")
print(f"\n🎯 Combined (Majority): {n_anomalies_combined} anomalies ({n_anomalies_combined/len(rfm)*100:.2f}%)")

"""---
<a id='12'></a>
# 1️⃣2️⃣ Conclusion & Business Insights

### সার্বিক ফলাফল ও ব্যবসায়িক সুপারিশ
"""

print("="*70)
print("                    📊 PROJECT SUMMARY                           ")
print("="*70)

print("\n📦 DATASET OVERVIEW")
print("-"*50)
print(f"   Total Transactions: {len(df_original):,}")
print(f"   Clean Transactions: {len(df):,}")
print(f"   Unique Customers: {len(rfm):,}")
print(f"   Total Revenue: £{df['TotalPrice'].sum():,.2f}")

print("\n🔗 ASSOCIATION RULES (FP-Growth)")
print("-"*50)
print(f"   Frequent Itemsets: {len(frequent_itemsets)}")
print(f"   Association Rules: {len(rules)}")
print(f"   Strong Rules: {len(strong_rules)}")

print("\n👥 CUSTOMER SEGMENTATION")
print("-"*50)
print(f"   Optimal Clusters (K-Means): {optimal_k}")
print(f"   Best Silhouette Score: {max(silhouette_scores):.4f}")
segment_dist = rfm['Segment'].value_counts()
for seg, count in segment_dist.items():
    print(f"   {seg}: {count} ({count/len(rfm)*100:.1f}%)")

print("\n🎯 CLASSIFICATION MODELS")
print("-"*50)
print(f"   Best Model: {results_df.iloc[0]['Model']}")
print(f"   Accuracy: {results_df.iloc[0]['Accuracy']:.4f}")
print(f"   F1-Score: {results_df.iloc[0]['F1-Score']:.4f}")
print(f"   ROC-AUC: {results_df.iloc[0]['ROC-AUC']:.4f}")

print("\n🎪 ENSEMBLE LEARNING")
print("-"*50)
print(f"   Best Ensemble: Stacking")
print(f"   Accuracy: {accuracy_score(y_test, y_pred_stacking):.4f}")
print(f"   F1-Score: {f1_score(y_test, y_pred_stacking):.4f}")

print("\n🚨 ANOMALY DETECTION")
print("-"*50)
print(f"   Total Anomalies (Combined): {n_anomalies_combined}")
print(f"   Anomaly Rate: {n_anomalies_combined/len(rfm)*100:.2f}%")

print("\n" + "="*70)

print("\n💼 BUSINESS RECOMMENDATIONS")
print("="*70)

print("""
1️⃣ CUSTOMER RETENTION
   • Focus on 'At Risk' and 'Cannot Lose Them' segments
   • Send personalized re-engagement campaigns
   • Offer loyalty discounts to Champions

2️⃣ PRODUCT BUNDLING
   • Use association rules for product recommendations
   • Create bundle offers for frequently bought together items
   • Implement "Customers also bought" feature

3️⃣ TARGETED MARKETING
   • High-value customers → Premium product promotions
   • New customers → Welcome offers and onboarding
   • Lost customers → Win-back campaigns

4️⃣ FRAUD PREVENTION
   • Monitor flagged anomalous transactions
   • Set up automated alerts for unusual patterns
   • Review high-value anomalous customers

5️⃣ INVENTORY MANAGEMENT
   • Stock top-selling products adequately
   • Plan for seasonal demand based on trends
   • Reduce stock for slow-moving items
""")

print("="*70)
print("                    ✅ PROJECT COMPLETED                         ")
print("="*70)

# Save final RFM dataset
rfm.to_csv('rfm_analysis_results.csv', index=False)
print("✅ RFM results saved to 'rfm_analysis_results.csv'")

# Download the file
from google.colab import files
files.download('rfm_analysis_results.csv')